//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AddParagraphType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AddParagraphType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}ParagraphType">
 *       &lt;sequence>
 *         &lt;element name="ParagraphTrace" type="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}AddParagraphTraceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Exclusion" type="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}AddExclusionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Verse" type="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}AddVerseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:be:fgov:ehealth:samws:v2:core}actionPeriod"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddParagraphType", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit", propOrder = {
    "paragraphTrace",
    "exclusion",
    "verse"
})
public class AddParagraphType
    extends ParagraphType
{

    @XmlElement(name = "ParagraphTrace", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected List<AddParagraphTraceType> paragraphTrace;
    @XmlElement(name = "Exclusion", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected List<AddExclusionType> exclusion;
    @XmlElement(name = "Verse", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected List<AddVerseType> verse;
    @XmlAttribute(name = "from", required = true)
    protected XMLGregorianCalendar from;
    @XmlAttribute(name = "to")
    protected XMLGregorianCalendar to;

    /**
     * Gets the value of the paragraphTrace property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paragraphTrace property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParagraphTrace().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddParagraphTraceType }
     *
     *
     */
    public List<AddParagraphTraceType> getParagraphTrace() {
        if (paragraphTrace == null) {
            paragraphTrace = new ArrayList<AddParagraphTraceType>();
        }
        return this.paragraphTrace;
    }

    /**
     * Gets the value of the exclusion property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exclusion property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExclusion().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddExclusionType }
     *
     *
     */
    public List<AddExclusionType> getExclusion() {
        if (exclusion == null) {
            exclusion = new ArrayList<AddExclusionType>();
        }
        return this.exclusion;
    }

    /**
     * Gets the value of the verse property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verse property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerse().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddVerseType }
     *
     *
     */
    public List<AddVerseType> getVerse() {
        if (verse == null) {
            verse = new ArrayList<AddVerseType>();
        }
        return this.verse;
    }

    /**
     * Gets the value of the from property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setFrom(XMLGregorianCalendar value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setTo(XMLGregorianCalendar value) {
        this.to = value;
    }

}
