//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmppNihdiType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AmppNihdiType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:actual:common}AmppKeyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:actual:common}AmppNihdiFields"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmppNihdiType", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common", propOrder = {
    "exFactoryPrice",
    "reimbursementCode",
    "cheap",
    "cheapest",
    "bigPackage",
    "index",
    "packingSizeGroup"
})
@XmlSeeAlso({
    AddAmppNihdiType.class
})
public class AmppNihdiType
    extends AmppKeyType
{

    @XmlElement(name = "ExFactoryPrice", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected BigDecimal exFactoryPrice;
    @XmlElement(name = "ReimbursementCode", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    @XmlSchemaType(name = "integer")
    protected Integer reimbursementCode;
    @XmlElement(name = "Cheap", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Boolean cheap;
    @XmlElement(name = "Cheapest", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Boolean cheapest;
    @XmlElement(name = "BigPackage", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Boolean bigPackage;
    @XmlElement(name = "Index", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected BigDecimal index;
    @XmlElement(name = "PackingSizeGroup", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Integer packingSizeGroup;

    /**
     * Gets the value of the exFactoryPrice property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getExFactoryPrice() {
        return exFactoryPrice;
    }

    /**
     * Sets the value of the exFactoryPrice property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setExFactoryPrice(BigDecimal value) {
        this.exFactoryPrice = value;
    }

    /**
     * Gets the value of the reimbursementCode property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getReimbursementCode() {
        return reimbursementCode;
    }

    /**
     * Sets the value of the reimbursementCode property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setReimbursementCode(Integer value) {
        this.reimbursementCode = value;
    }

    /**
     * Gets the value of the cheap property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCheap() {
        return cheap;
    }

    /**
     * Sets the value of the cheap property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCheap(Boolean value) {
        this.cheap = value;
    }

    /**
     * Gets the value of the cheapest property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCheapest() {
        return cheapest;
    }

    /**
     * Sets the value of the cheapest property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCheapest(Boolean value) {
        this.cheapest = value;
    }

    /**
     * Gets the value of the bigPackage property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isBigPackage() {
        return bigPackage;
    }

    /**
     * Sets the value of the bigPackage property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setBigPackage(Boolean value) {
        this.bigPackage = value;
    }

    /**
     * Gets the value of the index property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setIndex(BigDecimal value) {
        this.index = value;
    }

    /**
     * Gets the value of the packingSizeGroup property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getPackingSizeGroup() {
        return packingSizeGroup;
    }

    /**
     * Sets the value of the packingSizeGroup property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setPackingSizeGroup(Integer value) {
        this.packingSizeGroup = value;
    }

}
