//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BoundedParameterType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BoundedParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DosageParameterName" type="{urn:be:fgov:ehealth:samws:v2:core}String255Type"/>
 *         &lt;element name="LowerBound" type="{urn:be:fgov:ehealth:samws:v2:core}Decimal20d4Type" minOccurs="0"/>
 *         &lt;element name="UpperBound" type="{urn:be:fgov:ehealth:samws:v2:core}Decimal20d4Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundedParameterType", namespace = "urn:be:fgov:ehealth:samws:v2:virtual:common", propOrder = {
    "dosageParameterName",
    "lowerBound",
    "upperBound"
})
public class BoundedParameterType {

    @XmlElement(name = "DosageParameterName", namespace = "urn:be:fgov:ehealth:samws:v2:virtual:common", required = true)
    protected String dosageParameterName;
    @XmlElement(name = "LowerBound", namespace = "urn:be:fgov:ehealth:samws:v2:virtual:common")
    protected BigDecimal lowerBound;
    @XmlElement(name = "UpperBound", namespace = "urn:be:fgov:ehealth:samws:v2:virtual:common")
    protected BigDecimal upperBound;

    /**
     * Gets the value of the dosageParameterName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDosageParameterName() {
        return dosageParameterName;
    }

    /**
     * Sets the value of the dosageParameterName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDosageParameterName(String value) {
        this.dosageParameterName = value;
    }

    /**
     * Gets the value of the lowerBound property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getLowerBound() {
        return lowerBound;
    }

    /**
     * Sets the value of the lowerBound property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setLowerBound(BigDecimal value) {
        this.lowerBound = value;
    }

    /**
     * Gets the value of the upperBound property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getUpperBound() {
        return upperBound;
    }

    /**
     * Sets the value of the upperBound property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setUpperBound(BigDecimal value) {
        this.upperBound = value;
    }

}
