//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DmppDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DmppDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:export}DataPeriodType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:actual:common}DmppFields"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:actual:common}DmppReimbursementFields"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DmppDataType", propOrder = {
    "price",
    "cheap",
    "cheapest",
    "reimbursable",
    "cheapestCeilingPricesStatus5",
    "headOfTheCluster",
    "headOfTheClusterPricingUnitQuantity",
    "headOfTheClusterPricingUnitLabel"
})
public class DmppDataType
    extends DataPeriodType
{

    @XmlElement(name = "Price", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected BigDecimal price;
    @XmlElement(name = "Cheap", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Boolean cheap;
    @XmlElement(name = "Cheapest", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Boolean cheapest;
    @XmlElement(name = "Reimbursable", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected boolean reimbursable;
    @XmlElement(name = "CheapestCeilingPricesStatus5", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Boolean cheapestCeilingPricesStatus5;
    @XmlElement(name = "HeadOfTheCluster", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected String headOfTheCluster;
    @XmlElement(name = "HeadOfTheClusterPricingUnitQuantity", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected BigDecimal headOfTheClusterPricingUnitQuantity;
    @XmlElement(name = "HeadOfTheClusterPricingUnitLabel", namespace = "urn:be:fgov:ehealth:samws:v2:actual:common")
    protected Text255Type headOfTheClusterPricingUnitLabel;

    /**
     * Gets the value of the price property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the cheap property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCheap() {
        return cheap;
    }

    /**
     * Sets the value of the cheap property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCheap(Boolean value) {
        this.cheap = value;
    }

    /**
     * Gets the value of the cheapest property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCheapest() {
        return cheapest;
    }

    /**
     * Sets the value of the cheapest property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCheapest(Boolean value) {
        this.cheapest = value;
    }

    /**
     * Gets the value of the reimbursable property.
     *
     */
    public boolean isReimbursable() {
        return reimbursable;
    }

    /**
     * Sets the value of the reimbursable property.
     *
     */
    public void setReimbursable(boolean value) {
        this.reimbursable = value;
    }

    /**
     * Gets the value of the cheapestCeilingPricesStatus5 property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCheapestCeilingPricesStatus5() {
        return cheapestCeilingPricesStatus5;
    }

    /**
     * Sets the value of the cheapestCeilingPricesStatus5 property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCheapestCeilingPricesStatus5(Boolean value) {
        this.cheapestCeilingPricesStatus5 = value;
    }

    /**
     * Gets the value of the headOfTheCluster property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHeadOfTheCluster() {
        return headOfTheCluster;
    }

    /**
     * Sets the value of the headOfTheCluster property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHeadOfTheCluster(String value) {
        this.headOfTheCluster = value;
    }

    /**
     * Gets the value of the headOfTheClusterPricingUnitQuantity property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getHeadOfTheClusterPricingUnitQuantity() {
        return headOfTheClusterPricingUnitQuantity;
    }

    /**
     * Sets the value of the headOfTheClusterPricingUnitQuantity property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setHeadOfTheClusterPricingUnitQuantity(BigDecimal value) {
        this.headOfTheClusterPricingUnitQuantity = value;
    }

    /**
     * Gets the value of the headOfTheClusterPricingUnitLabel property.
     *
     * @return
     *     possible object is
     *     {@link Text255Type }
     *
     */
    public Text255Type getHeadOfTheClusterPricingUnitLabel() {
        return headOfTheClusterPricingUnitLabel;
    }

    /**
     * Sets the value of the headOfTheClusterPricingUnitLabel property.
     *
     * @param value
     *     allowed object is
     *     {@link Text255Type }
     *
     */
    public void setHeadOfTheClusterPricingUnitLabel(Text255Type value) {
        this.headOfTheClusterPricingUnitLabel = value;
    }

}
