//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExclusionKeyType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ExclusionKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ExclusionType" use="required" type="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}ExclusionTypeType" />
 *       &lt;attribute name="IdentifierNum" use="required" type="{urn:be:fgov:ehealth:samws:v2:core}String10Type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExclusionKeyType", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
@XmlSeeAlso({
    ExclusionFullDataType.class,
    ExclusionType.class
})
public class ExclusionKeyType {

    @XmlAttribute(name = "ExclusionType", required = true)
    protected ExclusionTypeType exclusionType;
    @XmlAttribute(name = "IdentifierNum", required = true)
    protected String identifierNum;

    /**
     * Gets the value of the exclusionType property.
     *
     * @return
     *     possible object is
     *     {@link ExclusionTypeType }
     *
     */
    public ExclusionTypeType getExclusionType() {
        return exclusionType;
    }

    /**
     * Sets the value of the exclusionType property.
     *
     * @param value
     *     allowed object is
     *     {@link ExclusionTypeType }
     *
     */
    public void setExclusionType(ExclusionTypeType value) {
        this.exclusionType = value;
    }

    /**
     * Gets the value of the identifierNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdentifierNum() {
        return identifierNum;
    }

    /**
     * Sets the value of the identifierNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdentifierNum(String value) {
        this.identifierNum = value;
    }

}
