//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImportedMedicinalProductPackageDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ImportedMedicinalProductPackageDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:export}DataPeriodType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:actual:imported}ImportedMedicinalProductPackageFields"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:export}ImportedMedicinalProductPackageReferenceFields"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportedMedicinalProductPackageDataType", propOrder = {
    "name",
    "country",
    "strength",
    "packSize",
    "notes",
    "cnk",
    "vmpCode",
    "activeSubstance",
    "pharmaceuticalFormCode",
    "routeOfAdministrationCode",
    "packagingTypeCode"
})
public class ImportedMedicinalProductPackageDataType
    extends DataPeriodType
{

    @XmlElement(name = "Name", namespace = "urn:be:fgov:ehealth:samws:v2:actual:imported", required = true)
    protected String name;
    @XmlElement(name = "Country", namespace = "urn:be:fgov:ehealth:samws:v2:actual:imported", required = true)
    protected String country;
    @XmlElement(name = "Strength", namespace = "urn:be:fgov:ehealth:samws:v2:actual:imported")
    protected String strength;
    @XmlElement(name = "PackSize", namespace = "urn:be:fgov:ehealth:samws:v2:actual:imported")
    protected String packSize;
    @XmlElement(name = "Notes", namespace = "urn:be:fgov:ehealth:samws:v2:actual:imported")
    protected String notes;
    @XmlElement(name = "CNK", namespace = "urn:be:fgov:ehealth:samws:v2:actual:imported")
    protected String cnk;
    @XmlElement(name = "VmpCode")
    protected VmpKeyType vmpCode;
    @XmlElement(name = "ActiveSubstance")
    protected List<SubstanceWithStandardsType> activeSubstance;
    @XmlElement(name = "PharmaceuticalFormCode")
    protected List<PharmaceuticalFormWithStandardsType> pharmaceuticalFormCode;
    @XmlElement(name = "RouteOfAdministrationCode")
    protected List<RouteOfAdministrationWithStandardsType> routeOfAdministrationCode;
    @XmlElement(name = "PackagingTypeCode")
    protected PackagingTypeType packagingTypeCode;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the strength property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStrength(String value) {
        this.strength = value;
    }

    /**
     * Gets the value of the packSize property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPackSize() {
        return packSize;
    }

    /**
     * Sets the value of the packSize property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPackSize(String value) {
        this.packSize = value;
    }

    /**
     * Gets the value of the notes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the cnk property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCNK() {
        return cnk;
    }

    /**
     * Sets the value of the cnk property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCNK(String value) {
        this.cnk = value;
    }

    /**
     * Gets the value of the vmpCode property.
     *
     * @return
     *     possible object is
     *     {@link VmpKeyType }
     *
     */
    public VmpKeyType getVmpCode() {
        return vmpCode;
    }

    /**
     * Sets the value of the vmpCode property.
     *
     * @param value
     *     allowed object is
     *     {@link VmpKeyType }
     *
     */
    public void setVmpCode(VmpKeyType value) {
        this.vmpCode = value;
    }

    /**
     * Gets the value of the activeSubstance property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activeSubstance property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActiveSubstance().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceWithStandardsType }
     *
     *
     */
    public List<SubstanceWithStandardsType> getActiveSubstance() {
        if (activeSubstance == null) {
            activeSubstance = new ArrayList<SubstanceWithStandardsType>();
        }
        return this.activeSubstance;
    }

    /**
     * Gets the value of the pharmaceuticalFormCode property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pharmaceuticalFormCode property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPharmaceuticalFormCode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PharmaceuticalFormWithStandardsType }
     *
     *
     */
    public List<PharmaceuticalFormWithStandardsType> getPharmaceuticalFormCode() {
        if (pharmaceuticalFormCode == null) {
            pharmaceuticalFormCode = new ArrayList<PharmaceuticalFormWithStandardsType>();
        }
        return this.pharmaceuticalFormCode;
    }

    /**
     * Gets the value of the routeOfAdministrationCode property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeOfAdministrationCode property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteOfAdministrationCode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteOfAdministrationWithStandardsType }
     *
     *
     */
    public List<RouteOfAdministrationWithStandardsType> getRouteOfAdministrationCode() {
        if (routeOfAdministrationCode == null) {
            routeOfAdministrationCode = new ArrayList<RouteOfAdministrationWithStandardsType>();
        }
        return this.routeOfAdministrationCode;
    }

    /**
     * Gets the value of the packagingTypeCode property.
     *
     * @return
     *     possible object is
     *     {@link PackagingTypeType }
     *
     */
    public PackagingTypeType getPackagingTypeCode() {
        return packagingTypeCode;
    }

    /**
     * Sets the value of the packagingTypeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link PackagingTypeType }
     *
     */
    public void setPackagingTypeCode(PackagingTypeType value) {
        this.packagingTypeCode = value;
    }

}
