//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NameTypeKeyType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NameTypeKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="NameTypeCV" use="required" type="{urn:be:fgov:ehealth:samws:v2:core}String6Type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameTypeKeyType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
public class NameTypeKeyType {

    @XmlAttribute(name = "NameTypeCV", required = true)
    protected String nameTypeCV;

    /**
     * Gets the value of the nameTypeCV property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameTypeCV() {
        return nameTypeCV;
    }

    /**
     * Sets the value of the nameTypeCV property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameTypeCV(String value) {
        this.nameTypeCV = value;
    }

}
