//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NameTranslationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NameTranslationType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}NameTranslationKeyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}NameTranslationFields"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameTranslationType", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit", propOrder = {
    "shortText",
    "longText",
    "longBinaryText",
    "addressUrl"
})
@XmlSeeAlso({
    AddNameTranslationType.class
})
public class NameTranslationType
    extends NameTranslationKeyType
{

    @XmlElement(name = "ShortText", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected String shortText;
    @XmlElement(name = "LongText", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected String longText;
    @XmlElement(name = "LongBinaryText", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected byte[] longBinaryText;
    @XmlElement(name = "AddressUrl", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected String addressUrl;

    /**
     * Gets the value of the shortText property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getShortText() {
        return shortText;
    }

    /**
     * Sets the value of the shortText property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setShortText(String value) {
        this.shortText = value;
    }

    /**
     * Gets the value of the longText property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLongText() {
        return longText;
    }

    /**
     * Sets the value of the longText property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLongText(String value) {
        this.longText = value;
    }

    /**
     * Gets the value of the longBinaryText property.
     *
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLongBinaryText() {
        return longBinaryText;
    }

    /**
     * Sets the value of the longBinaryText property.
     *
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLongBinaryText(byte[] value) {
        this.longBinaryText = value;
    }

    /**
     * Gets the value of the addressUrl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddressUrl() {
        return addressUrl;
    }

    /**
     * Sets the value of the addressUrl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddressUrl(String value) {
        this.addressUrl = value;
    }

}
