//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonMedicinalProductDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NonMedicinalProductDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:export}DataPeriodType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:nonmedicinal:common}NonMedicinalProductFields"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:nonmedicinal:common}NonMedicinalProductPricingFields" minOccurs="0"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:nonmedicinal:common}NonMedicinalProductNihdiFields" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonMedicinalProductDataType", propOrder = {
    "name",
    "category",
    "commercialStatus",
    "producer",
    "distributor",
    "exFactoryPrice",
    "publicPrice",
    "contraceptive"
})
public class NonMedicinalProductDataType
    extends DataPeriodType
{

    @XmlElement(name = "Name", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common", required = true)
    protected Text255Type name;
    @XmlElement(name = "Category", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common", required = true)
    protected String category;
    @XmlElement(name = "CommercialStatus", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common", required = true)
    protected String commercialStatus;
    @XmlElement(name = "Producer", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common", required = true)
    protected TextType producer;
    @XmlElement(name = "Distributor", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common")
    protected TextType distributor;
    @XmlElement(name = "ExFactoryPrice", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common")
    protected BigDecimal exFactoryPrice;
    @XmlElement(name = "PublicPrice", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common")
    protected BigDecimal publicPrice;
    @XmlElement(name = "Contraceptive", namespace = "urn:be:fgov:ehealth:samws:v2:nonmedicinal:common")
    protected Boolean contraceptive;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link Text255Type }
     *
     */
    public Text255Type getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link Text255Type }
     *
     */
    public void setName(Text255Type value) {
        this.name = value;
    }

    /**
     * Gets the value of the category property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the commercialStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCommercialStatus() {
        return commercialStatus;
    }

    /**
     * Sets the value of the commercialStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCommercialStatus(String value) {
        this.commercialStatus = value;
    }

    /**
     * Gets the value of the producer property.
     *
     * @return
     *     possible object is
     *     {@link TextType }
     *
     */
    public TextType getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     *
     * @param value
     *     allowed object is
     *     {@link TextType }
     *
     */
    public void setProducer(TextType value) {
        this.producer = value;
    }

    /**
     * Gets the value of the distributor property.
     *
     * @return
     *     possible object is
     *     {@link TextType }
     *
     */
    public TextType getDistributor() {
        return distributor;
    }

    /**
     * Sets the value of the distributor property.
     *
     * @param value
     *     allowed object is
     *     {@link TextType }
     *
     */
    public void setDistributor(TextType value) {
        this.distributor = value;
    }

    /**
     * Gets the value of the exFactoryPrice property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getExFactoryPrice() {
        return exFactoryPrice;
    }

    /**
     * Sets the value of the exFactoryPrice property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setExFactoryPrice(BigDecimal value) {
        this.exFactoryPrice = value;
    }

    /**
     * Gets the value of the publicPrice property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getPublicPrice() {
        return publicPrice;
    }

    /**
     * Sets the value of the publicPrice property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setPublicPrice(BigDecimal value) {
        this.publicPrice = value;
    }

    /**
     * Gets the value of the contraceptive property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isContraceptive() {
        return contraceptive;
    }

    /**
     * Sets the value of the contraceptive property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setContraceptive(Boolean value) {
        this.contraceptive = value;
    }

}
