//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.taktik.icure.be.samv2v6.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemoveParagraphRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoveParagraphRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Paragraph" type="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}RemoveParagraphType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoveParagraphRequestType", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit", propOrder = {
    "paragraph"
})
public class RemoveParagraphRequestType {

    @XmlElement(name = "Paragraph", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit", required = true)
    protected RemoveParagraphType paragraph;

    /**
     * Gets the value of the paragraph property.
     * 
     * @return
     *     possible object is
     *     {@link RemoveParagraphType }
     *     
     */
    public RemoveParagraphType getParagraph() {
        return paragraph;
    }

    /**
     * Sets the value of the paragraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoveParagraphType }
     *     
     */
    public void setParagraph(RemoveParagraphType value) {
        this.paragraph = value;
    }

}
