//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SetNihdiReferencesRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SetNihdiReferencesRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}SetNihdiEntities"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}SetChapterIVEntities"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetNihdiReferencesRequestType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata", propOrder = {
    "appendix",
    "formCategory",
    "parameter",
    "reimbursementCriterion",
    "professionalCode",
    "appendixType",
    "formType",
    "nameType",
    "legalReferencePathToParagraph"
})
public class SetNihdiReferencesRequestType {

    @XmlElement(name = "Appendix", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<AppendixType> appendix;
    @XmlElement(name = "FormCategory", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<FormCategoryType> formCategory;
    @XmlElement(name = "Parameter", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ParameterType> parameter;
    @XmlElement(name = "ReimbursementCriterion", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ReimbursementCriterionType> reimbursementCriterion;
    @XmlElement(name = "ProfessionalCode", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ProfessionalCodeType> professionalCode;
    @XmlElement(name = "AppendixType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<AppendixTypeType> appendixType;
    @XmlElement(name = "FormType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<FormTypeType> formType;
    @XmlElement(name = "NameType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<NameTypeType> nameType;
    @XmlElement(name = "LegalReferencePathToParagraph", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<LegalReferencePathToParagraphType> legalReferencePathToParagraph;

    /**
     * Gets the value of the appendix property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appendix property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppendix().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppendixType }
     *
     *
     */
    public List<AppendixType> getAppendix() {
        if (appendix == null) {
            appendix = new ArrayList<AppendixType>();
        }
        return this.appendix;
    }

    /**
     * Gets the value of the formCategory property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formCategory property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormCategory().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormCategoryType }
     *
     *
     */
    public List<FormCategoryType> getFormCategory() {
        if (formCategory == null) {
            formCategory = new ArrayList<FormCategoryType>();
        }
        return this.formCategory;
    }

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     *
     *
     */
    public List<ParameterType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterType>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the reimbursementCriterion property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reimbursementCriterion property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReimbursementCriterion().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReimbursementCriterionType }
     *
     *
     */
    public List<ReimbursementCriterionType> getReimbursementCriterion() {
        if (reimbursementCriterion == null) {
            reimbursementCriterion = new ArrayList<ReimbursementCriterionType>();
        }
        return this.reimbursementCriterion;
    }

    /**
     * Gets the value of the professionalCode property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the professionalCode property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfessionalCode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfessionalCodeType }
     *
     *
     */
    public List<ProfessionalCodeType> getProfessionalCode() {
        if (professionalCode == null) {
            professionalCode = new ArrayList<ProfessionalCodeType>();
        }
        return this.professionalCode;
    }

    /**
     * Gets the value of the appendixType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appendixType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppendixType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppendixTypeType }
     *
     *
     */
    public List<AppendixTypeType> getAppendixType() {
        if (appendixType == null) {
            appendixType = new ArrayList<AppendixTypeType>();
        }
        return this.appendixType;
    }

    /**
     * Gets the value of the formType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormTypeType }
     *
     *
     */
    public List<FormTypeType> getFormType() {
        if (formType == null) {
            formType = new ArrayList<FormTypeType>();
        }
        return this.formType;
    }

    /**
     * Gets the value of the nameType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameTypeType }
     *
     *
     */
    public List<NameTypeType> getNameType() {
        if (nameType == null) {
            nameType = new ArrayList<NameTypeType>();
        }
        return this.nameType;
    }

    /**
     * Gets the value of the legalReferencePathToParagraph property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legalReferencePathToParagraph property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegalReferencePathToParagraph().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LegalReferencePathToParagraphType }
     *
     *
     */
    public List<LegalReferencePathToParagraphType> getLegalReferencePathToParagraph() {
        if (legalReferencePathToParagraph == null) {
            legalReferencePathToParagraph = new ArrayList<LegalReferencePathToParagraphType>();
        }
        return this.legalReferencePathToParagraph;
    }

}
