//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SexRestrictedType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SexRestrictedType">
 *   &lt;restriction base="{urn:be:fgov:ehealth:samws:v2:core}CharacterType">
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="M"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "SexRestrictedType", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
@XmlEnum
public enum SexRestrictedType {

    F,
    M;

    public String value() {
        return name();
    }

    public static SexRestrictedType fromValue(String v) {
        return valueOf(v);
    }

}
