//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnsetNihdiReferencesRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UnsetNihdiReferencesRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Appendix" type="{urn:be:fgov:ehealth:samws:v2:refdata}AppendixKeyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FormCategory" type="{urn:be:fgov:ehealth:samws:v2:refdata}FormCategoryKeyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Parameter" type="{urn:be:fgov:ehealth:samws:v2:refdata}ParameterKeyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReimbursementCriterion" type="{urn:be:fgov:ehealth:samws:v2:refdata}ReimbursementCriterionKeyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}UnsetChapterIVEntities"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnsetNihdiReferencesRequestType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata", propOrder = {
    "appendix",
    "formCategory",
    "parameter",
    "reimbursementCriterion",
    "professionalCode",
    "appendixType",
    "formType",
    "nameType"
})
public class UnsetNihdiReferencesRequestType {

    @XmlElement(name = "Appendix", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<AppendixKeyType> appendix;
    @XmlElement(name = "FormCategory", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<FormCategoryKeyType> formCategory;
    @XmlElement(name = "Parameter", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ParameterKeyType> parameter;
    @XmlElement(name = "ReimbursementCriterion", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ReimbursementCriterionKeyType> reimbursementCriterion;
    @XmlElement(name = "ProfessionalCode", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ProfessionalCodeKeyType> professionalCode;
    @XmlElement(name = "AppendixType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<AppendixTypeKeyType> appendixType;
    @XmlElement(name = "FormType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<FormTypeKeyType> formType;
    @XmlElement(name = "NameType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<NameTypeKeyType> nameType;

    /**
     * Gets the value of the appendix property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appendix property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppendix().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppendixKeyType }
     *
     *
     */
    public List<AppendixKeyType> getAppendix() {
        if (appendix == null) {
            appendix = new ArrayList<AppendixKeyType>();
        }
        return this.appendix;
    }

    /**
     * Gets the value of the formCategory property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formCategory property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormCategory().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormCategoryKeyType }
     *
     *
     */
    public List<FormCategoryKeyType> getFormCategory() {
        if (formCategory == null) {
            formCategory = new ArrayList<FormCategoryKeyType>();
        }
        return this.formCategory;
    }

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterKeyType }
     *
     *
     */
    public List<ParameterKeyType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterKeyType>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the reimbursementCriterion property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reimbursementCriterion property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReimbursementCriterion().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReimbursementCriterionKeyType }
     *
     *
     */
    public List<ReimbursementCriterionKeyType> getReimbursementCriterion() {
        if (reimbursementCriterion == null) {
            reimbursementCriterion = new ArrayList<ReimbursementCriterionKeyType>();
        }
        return this.reimbursementCriterion;
    }

    /**
     * Gets the value of the professionalCode property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the professionalCode property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfessionalCode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfessionalCodeKeyType }
     *
     *
     */
    public List<ProfessionalCodeKeyType> getProfessionalCode() {
        if (professionalCode == null) {
            professionalCode = new ArrayList<ProfessionalCodeKeyType>();
        }
        return this.professionalCode;
    }

    /**
     * Gets the value of the appendixType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appendixType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppendixType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppendixTypeKeyType }
     *
     *
     */
    public List<AppendixTypeKeyType> getAppendixType() {
        if (appendixType == null) {
            appendixType = new ArrayList<AppendixTypeKeyType>();
        }
        return this.appendixType;
    }

    /**
     * Gets the value of the formType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormTypeKeyType }
     *
     *
     */
    public List<FormTypeKeyType> getFormType() {
        if (formType == null) {
            formType = new ArrayList<FormTypeKeyType>();
        }
        return this.formType;
    }

    /**
     * Gets the value of the nameType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameTypeKeyType }
     *
     *
     */
    public List<NameTypeKeyType> getNameType() {
        if (nameType == null) {
            nameType = new ArrayList<NameTypeKeyType>();
        }
        return this.nameType;
    }

}
