//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package org.taktik.icure.be.samv2v6.entities;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VerseDataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VerseDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:export}DataPeriodType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:chapteriv:submit}VerseFields"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerseDataType", propOrder = {
    "verseNum",
    "verseSeqParent",
    "verseLevel",
    "verseType",
    "checkBoxInd",
    "minCheckNum",
    "andClauseNum",
    "textFr",
    "textNl",
    "requestType",
    "agreementTerm",
    "agreementTermUnit",
    "maxPackageNumber",
    "purchasingAdvisorQualList",
    "legalReference",
    "modificationDate",
    "agreementYearMax",
    "agreementRenewalMax",
    "sexRestricted",
    "minimumAgeAuthorized",
    "minimumAgeAuthorizedUnit",
    "maximumAgeAuthorized",
    "maximumAgeAuthorizedUnit",
    "maximumContentQuantity",
    "maximumContentUnit",
    "maximumStrengthQuantity",
    "maximumStrengthUnit",
    "maximumDurationQuantity",
    "maximumDurationUnit",
    "otherAddedDocumentInd"
})
public class VerseDataType
    extends DataPeriodType
{

    @XmlElement(name = "VerseNum", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected int verseNum;
    @XmlElement(name = "VerseSeqParent", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected int verseSeqParent;
    @XmlElement(name = "VerseLevel", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected int verseLevel;
    @XmlElement(name = "VerseType", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "string")
    protected VerseTypeType verseType;
    @XmlElement(name = "CheckBoxInd", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected boolean checkBoxInd;
    @XmlElement(name = "MinCheckNum", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected Integer minCheckNum;
    @XmlElement(name = "AndClauseNum", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected Integer andClauseNum;
    @XmlElement(name = "TextFr", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit", required = true)
    protected String textFr;
    @XmlElement(name = "TextNl", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit", required = true)
    protected String textNl;
    @XmlElement(name = "RequestType", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "string")
    protected RequestTypeType requestType;
    @XmlElement(name = "AgreementTerm", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected Integer agreementTerm;
    @XmlElement(name = "AgreementTermUnit", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "string")
    protected DurationUnitType agreementTermUnit;
    @XmlElement(name = "MaxPackageNumber", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected Integer maxPackageNumber;
    @XmlElement(name = "PurchasingAdvisorQualList", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected String purchasingAdvisorQualList;
    @XmlElement(name = "LegalReference", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected String legalReference;
    @XmlElement(name = "ModificationDate", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar modificationDate;
    @XmlElement(name = "AgreementYearMax", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected Integer agreementYearMax;
    @XmlElement(name = "AgreementRenewalMax", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected Integer agreementRenewalMax;
    @XmlElement(name = "SexRestricted", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "string")
    protected SexRestrictedType sexRestricted;
    @XmlElement(name = "MinimumAgeAuthorized", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected BigDecimal minimumAgeAuthorized;
    @XmlElement(name = "MinimumAgeAuthorizedUnit", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "string")
    protected DurationUnitType minimumAgeAuthorizedUnit;
    @XmlElement(name = "MaximumAgeAuthorized", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected BigDecimal maximumAgeAuthorized;
    @XmlElement(name = "MaximumAgeAuthorizedUnit", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "string")
    protected DurationUnitType maximumAgeAuthorizedUnit;
    @XmlElement(name = "MaximumContentQuantity", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected BigDecimal maximumContentQuantity;
    @XmlElement(name = "MaximumContentUnit", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected String maximumContentUnit;
    @XmlElement(name = "MaximumStrengthQuantity", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected BigDecimal maximumStrengthQuantity;
    @XmlElement(name = "MaximumStrengthUnit", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected String maximumStrengthUnit;
    @XmlElement(name = "MaximumDurationQuantity", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected BigDecimal maximumDurationQuantity;
    @XmlElement(name = "MaximumDurationUnit", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    @XmlSchemaType(name = "string")
    protected DurationUnitType maximumDurationUnit;
    @XmlElement(name = "OtherAddedDocumentInd", namespace = "urn:be:fgov:ehealth:samws:v2:chapteriv:submit")
    protected Boolean otherAddedDocumentInd;

    /**
     * Gets the value of the verseNum property.
     *
     */
    public int getVerseNum() {
        return verseNum;
    }

    /**
     * Sets the value of the verseNum property.
     *
     */
    public void setVerseNum(int value) {
        this.verseNum = value;
    }

    /**
     * Gets the value of the verseSeqParent property.
     *
     */
    public int getVerseSeqParent() {
        return verseSeqParent;
    }

    /**
     * Sets the value of the verseSeqParent property.
     *
     */
    public void setVerseSeqParent(int value) {
        this.verseSeqParent = value;
    }

    /**
     * Gets the value of the verseLevel property.
     *
     */
    public int getVerseLevel() {
        return verseLevel;
    }

    /**
     * Sets the value of the verseLevel property.
     *
     */
    public void setVerseLevel(int value) {
        this.verseLevel = value;
    }

    /**
     * Gets the value of the verseType property.
     *
     * @return
     *     possible object is
     *     {@link VerseTypeType }
     *
     */
    public VerseTypeType getVerseType() {
        return verseType;
    }

    /**
     * Sets the value of the verseType property.
     *
     * @param value
     *     allowed object is
     *     {@link VerseTypeType }
     *
     */
    public void setVerseType(VerseTypeType value) {
        this.verseType = value;
    }

    /**
     * Gets the value of the checkBoxInd property.
     *
     */
    public boolean isCheckBoxInd() {
        return checkBoxInd;
    }

    /**
     * Sets the value of the checkBoxInd property.
     *
     */
    public void setCheckBoxInd(boolean value) {
        this.checkBoxInd = value;
    }

    /**
     * Gets the value of the minCheckNum property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getMinCheckNum() {
        return minCheckNum;
    }

    /**
     * Sets the value of the minCheckNum property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setMinCheckNum(Integer value) {
        this.minCheckNum = value;
    }

    /**
     * Gets the value of the andClauseNum property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getAndClauseNum() {
        return andClauseNum;
    }

    /**
     * Sets the value of the andClauseNum property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setAndClauseNum(Integer value) {
        this.andClauseNum = value;
    }

    /**
     * Gets the value of the textFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTextFr() {
        return textFr;
    }

    /**
     * Sets the value of the textFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTextFr(String value) {
        this.textFr = value;
    }

    /**
     * Gets the value of the textNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTextNl() {
        return textNl;
    }

    /**
     * Sets the value of the textNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTextNl(String value) {
        this.textNl = value;
    }

    /**
     * Gets the value of the requestType property.
     *
     * @return
     *     possible object is
     *     {@link RequestTypeType }
     *
     */
    public RequestTypeType getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     *
     * @param value
     *     allowed object is
     *     {@link RequestTypeType }
     *
     */
    public void setRequestType(RequestTypeType value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the agreementTerm property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getAgreementTerm() {
        return agreementTerm;
    }

    /**
     * Sets the value of the agreementTerm property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setAgreementTerm(Integer value) {
        this.agreementTerm = value;
    }

    /**
     * Gets the value of the agreementTermUnit property.
     *
     * @return
     *     possible object is
     *     {@link DurationUnitType }
     *
     */
    public DurationUnitType getAgreementTermUnit() {
        return agreementTermUnit;
    }

    /**
     * Sets the value of the agreementTermUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link DurationUnitType }
     *
     */
    public void setAgreementTermUnit(DurationUnitType value) {
        this.agreementTermUnit = value;
    }

    /**
     * Gets the value of the maxPackageNumber property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getMaxPackageNumber() {
        return maxPackageNumber;
    }

    /**
     * Sets the value of the maxPackageNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setMaxPackageNumber(Integer value) {
        this.maxPackageNumber = value;
    }

    /**
     * Gets the value of the purchasingAdvisorQualList property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPurchasingAdvisorQualList() {
        return purchasingAdvisorQualList;
    }

    /**
     * Sets the value of the purchasingAdvisorQualList property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPurchasingAdvisorQualList(String value) {
        this.purchasingAdvisorQualList = value;
    }

    /**
     * Gets the value of the legalReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLegalReference() {
        return legalReference;
    }

    /**
     * Sets the value of the legalReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLegalReference(String value) {
        this.legalReference = value;
    }

    /**
     * Gets the value of the modificationDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getModificationDate() {
        return modificationDate;
    }

    /**
     * Sets the value of the modificationDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setModificationDate(XMLGregorianCalendar value) {
        this.modificationDate = value;
    }

    /**
     * Gets the value of the agreementYearMax property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getAgreementYearMax() {
        return agreementYearMax;
    }

    /**
     * Sets the value of the agreementYearMax property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setAgreementYearMax(Integer value) {
        this.agreementYearMax = value;
    }

    /**
     * Gets the value of the agreementRenewalMax property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getAgreementRenewalMax() {
        return agreementRenewalMax;
    }

    /**
     * Sets the value of the agreementRenewalMax property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setAgreementRenewalMax(Integer value) {
        this.agreementRenewalMax = value;
    }

    /**
     * Gets the value of the sexRestricted property.
     *
     * @return
     *     possible object is
     *     {@link SexRestrictedType }
     *
     */
    public SexRestrictedType getSexRestricted() {
        return sexRestricted;
    }

    /**
     * Sets the value of the sexRestricted property.
     *
     * @param value
     *     allowed object is
     *     {@link SexRestrictedType }
     *
     */
    public void setSexRestricted(SexRestrictedType value) {
        this.sexRestricted = value;
    }

    /**
     * Gets the value of the minimumAgeAuthorized property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getMinimumAgeAuthorized() {
        return minimumAgeAuthorized;
    }

    /**
     * Sets the value of the minimumAgeAuthorized property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setMinimumAgeAuthorized(BigDecimal value) {
        this.minimumAgeAuthorized = value;
    }

    /**
     * Gets the value of the minimumAgeAuthorizedUnit property.
     *
     * @return
     *     possible object is
     *     {@link DurationUnitType }
     *
     */
    public DurationUnitType getMinimumAgeAuthorizedUnit() {
        return minimumAgeAuthorizedUnit;
    }

    /**
     * Sets the value of the minimumAgeAuthorizedUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link DurationUnitType }
     *
     */
    public void setMinimumAgeAuthorizedUnit(DurationUnitType value) {
        this.minimumAgeAuthorizedUnit = value;
    }

    /**
     * Gets the value of the maximumAgeAuthorized property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getMaximumAgeAuthorized() {
        return maximumAgeAuthorized;
    }

    /**
     * Sets the value of the maximumAgeAuthorized property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setMaximumAgeAuthorized(BigDecimal value) {
        this.maximumAgeAuthorized = value;
    }

    /**
     * Gets the value of the maximumAgeAuthorizedUnit property.
     *
     * @return
     *     possible object is
     *     {@link DurationUnitType }
     *
     */
    public DurationUnitType getMaximumAgeAuthorizedUnit() {
        return maximumAgeAuthorizedUnit;
    }

    /**
     * Sets the value of the maximumAgeAuthorizedUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link DurationUnitType }
     *
     */
    public void setMaximumAgeAuthorizedUnit(DurationUnitType value) {
        this.maximumAgeAuthorizedUnit = value;
    }

    /**
     * Gets the value of the maximumContentQuantity property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getMaximumContentQuantity() {
        return maximumContentQuantity;
    }

    /**
     * Sets the value of the maximumContentQuantity property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setMaximumContentQuantity(BigDecimal value) {
        this.maximumContentQuantity = value;
    }

    /**
     * Gets the value of the maximumContentUnit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMaximumContentUnit() {
        return maximumContentUnit;
    }

    /**
     * Sets the value of the maximumContentUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMaximumContentUnit(String value) {
        this.maximumContentUnit = value;
    }

    /**
     * Gets the value of the maximumStrengthQuantity property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getMaximumStrengthQuantity() {
        return maximumStrengthQuantity;
    }

    /**
     * Sets the value of the maximumStrengthQuantity property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setMaximumStrengthQuantity(BigDecimal value) {
        this.maximumStrengthQuantity = value;
    }

    /**
     * Gets the value of the maximumStrengthUnit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMaximumStrengthUnit() {
        return maximumStrengthUnit;
    }

    /**
     * Sets the value of the maximumStrengthUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMaximumStrengthUnit(String value) {
        this.maximumStrengthUnit = value;
    }

    /**
     * Gets the value of the maximumDurationQuantity property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getMaximumDurationQuantity() {
        return maximumDurationQuantity;
    }

    /**
     * Sets the value of the maximumDurationQuantity property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setMaximumDurationQuantity(BigDecimal value) {
        this.maximumDurationQuantity = value;
    }

    /**
     * Gets the value of the maximumDurationUnit property.
     *
     * @return
     *     possible object is
     *     {@link DurationUnitType }
     *
     */
    public DurationUnitType getMaximumDurationUnit() {
        return maximumDurationUnit;
    }

    /**
     * Sets the value of the maximumDurationUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link DurationUnitType }
     *
     */
    public void setMaximumDurationUnit(DurationUnitType value) {
        this.maximumDurationUnit = value;
    }

    /**
     * Gets the value of the otherAddedDocumentInd property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isOtherAddedDocumentInd() {
        return otherAddedDocumentInd;
    }

    /**
     * Sets the value of the otherAddedDocumentInd property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setOtherAddedDocumentInd(Boolean value) {
        this.otherAddedDocumentInd = value;
    }

}
