{{- if .Values.images.kmehr.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: "{{ template "fullname" . }}-kmehr"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "kmehr"
spec:
    replicas: {{ .Values.images.kmehr.replicaCount }}
    selector:
        matchLabels:
            app: {{ template "name" . }}
            release: {{ .Release.Name }}
            component: "kmehr"
    template:
        metadata:
            labels:
                app: {{ template "name" . }}
                release: {{ .Release.Name }}
                component: "kmehr"
        spec:
            containers:
                -   name: "{{ .Chart.Name }}-kmehr"
                    image: "{{ .Values.images.kmehr.repository }}:{{ .Values.images.kmehr.tag | default .Chart.Version }}"
                    imagePullPolicy: "{{ .Values.pullPolicy }}"
                    ports:
                        -   containerPort: {{ .Values.images.kmehr.servicePort }}
                            name: http
                        -   containerPort: 5701
                            name: hz1
                      {{- if or .Values.images.kmehr.debug .Values.images.kmehr.debugsuspend }}
                        -   containerPort: 5005
                            name: "jvm-debug"
                      {{- end }}
                    env:
                        -   name: SPRING_PROFILES_ACTIVE
                            value: "kmehr"
                        -   name: JAVA_OPTS
                            value: "{{ .Values.images.kmehr.javaOpts }}{{ if .Values.images.kmehr.debug }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005{{ end }}{{ if .Values.images.kmehr.debugsuspend }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005{{ end }}"
                        -   name: ICURE_COUCHDB_URL
                            value: "{{ .Values.couchdbUrl }}:{{ .Values.couchdbPortNumber }}"
                        -   name: JWT_AUTH_PRIV_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: authPriv
                                    name: icure-jwt-key

                        -   name: JWT_AUTH_PUB_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: authPub
                                    name: icure-jwt-key

                        -   name: JWT_REFRESH_PRIV_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: refreshPriv
                                    name: icure-jwt-key

                        -   name: JWT_REFRESH_PUB_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: refreshPub
                                    name: icure-jwt-key

                      {{- range $key, $value := .Values.images.kmehr.env }}
                        -   name: "{{ $key }}"
                            value: "{{ $value }}"
                      {{- end }}
                    resources:
                        requests:
                            memory: {{ .Values.images.kmehr.memoryRequest | quote }}
                          {{- if .Values.images.kmehr.cpuRequest }}
                            cpu: {{ .Values.images.kmehr.cpuRequest | quote }}
                          {{- end }}
                        limits:
                            memory: {{ .Values.images.kmehr.memoryLimit | quote }}
                          {{- if .Values.images.kmehr.cpuLimit }}
                            cpu: {{ .Values.images.kmehr.cpuLimit | quote }}
                          {{- end }}
                    {{- if .Values.images.kmehr.readiness }}
                    readinessProbe:
                        httpGet:
                            path: /actuator/health
                            port: 8080
                        initialDelaySeconds: 20
                        periodSeconds: 10
                        timeoutSeconds: 5
                        successThreshold: 2
                        failureThreshold: 3
                    {{- end }}
                    {{- if .Values.images.kmehr.liveness }}
                    livenessProbe:
                        httpGet:
                            path: /actuator/health
                            port: 8080
                        initialDelaySeconds: 300
                        periodSeconds: 30
                        timeoutSeconds: 8
                        successThreshold: 1
                        failureThreshold: 3
                    {{- end }}
            imagePullSecrets:
                -   name: regsecret
  {{- end }}
