{{- if .Values.images.module.replicaCount }}
apiVersion: v1
kind: Service
metadata:
    name: "{{ template "fullname" . }}-kmehr-module"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "kmehr-module"
    {{- if or .Values.images.module.service.annotations .Values.images.module.metrics.enabled }}
    annotations:
      {{- if .Values.images.module.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.images.module.metrics.port | default (.Values.images.module.servicePort | default 8080) | quote }}
        prometheus.io/path: {{ .Values.images.module.metrics.path | default "/actuator/prometheus" | quote }}
      {{- end }}
      {{- with .Values.images.module.service.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
spec:
    type: {{ .Values.images.module.service.type | default "ClusterIP" }}
    ports:
        -   protocol: TCP
            port: {{ .Values.images.module.servicePort | default 8080 }}
            name: http
            targetPort: http
    selector:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: "kmehr-module"
{{- end }}
