{{- if .Values.images.sam.replicaCount }}
apiVersion: v1
kind: Service
metadata:
    name: "{{ template "fullname" . }}-sam"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "sam"
spec:
    ports:
        -   protocol: TCP
            port: {{ .Values.images.sam.servicePort }}
            name: http
            targetPort: http
        -   protocol: TCP
            port: 5701
            name: hz1
            targetPort: hz1
    selector:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: "sam"
  {{- end }}
